(function () {
  'use strict';
  var cfg = window.AVITOLOG_SUPABASE || {};
  var sessionKey = 'avitolog_backend_preview_session';
  var summary = document.getElementById('mapSummary');
  var groups = document.getElementById('mapGroups');
  var labels = { cash_payments:'Касса и оплаты', projects_tasks:'Проекты и задачи', goals_sales:'Цели и продажи', crm:'CRM', advertising:'Реклама', documents:'КП и договоры', settings_other:'Настройки и прочее' };
  var activeChecksum = '';
  function getSession(){ try{return JSON.parse(sessionStorage.getItem(sessionKey)||'null');}catch(e){return null;} }
  async function loadMap(token) {
    summary.textContent = 'Разбираю snapshot без записи...';
    var response = await fetch('http://127.0.0.1:8787/api/migration/data-inventory', {headers:{Authorization:'Bearer '+token}});
    var data = await response.json(); if(!response.ok||!data.ok) throw new Error(data.error||('HTTP '+response.status));
    var inventory=data.inventory; activeChecksum=data.snapshot.checksum; summary.textContent='DRY RUN · ключей: '+inventory.keyCount+' · объём: '+Math.round(inventory.totalBytes/1024)+' КБ · checksum: '+data.snapshot.checksum;
    groups.innerHTML=inventory.groups.map(function(g){return '<section class="group"><b>'+String(labels[g.category]||g.category)+'</b><p>Ключей: '+g.keys+'<br>Живых: '+g.liveKeys+'<br>Месячных снимков: '+g.monthlyKeys+'<br>Записей/элементов: '+g.records+'</p><span class="muted">'+Math.round(g.bytes/1024)+' КБ</span></section>';}).join('');
    var cashResponse=await fetch('http://127.0.0.1:8787/api/migration/cash-preview',{headers:{Authorization:'Bearer '+token}});
    var cashData=await cashResponse.json();if(!cashResponse.ok||!cashData.ok)throw new Error(cashData.error||('HTTP '+cashResponse.status));
    var cash=cashData.preview;var lines=['Правило: '+cash.rule,'Наборов: '+cash.totals.datasets+' (живых: '+cash.totals.liveDatasets+', месячных: '+cash.totals.monthlyDatasets+', точных дублей: '+cash.totals.exactDuplicateDatasets+')',''];
    cash.datasets.forEach(function(d){var money=d.role==='sasha'?('доля paid '+d.paid.toLocaleString('ru-RU')+' ₽ · сделки soldFor '+d.soldFor.toLocaleString('ru-RU')+' ₽ · toAgent '+d.toAgent.toLocaleString('ru-RU')+' ₽'):('paid '+d.paid.toLocaleString('ru-RU')+' ₽');lines.push((d.month||'LIVE')+' · '+d.role+' · строк '+d.rows+' · '+money+' · ожидается '+d.expected.toLocaleString('ru-RU')+' ₽ · история '+d.historyPayments+' платежей / '+d.historyAmount.toLocaleString('ru-RU')+' ₽'+(d.exactDuplicateDataset?' · ТОЧНЫЙ ДУБЛЬ':'')+'\n'+d.key);});
    document.getElementById('cashPreviewText').textContent=lines.join('\n');document.getElementById('cashPreview').classList.remove('off');
    var importResponse=await fetch('http://127.0.0.1:8787/api/migration/cash-import-preview',{headers:{Authorization:'Bearer '+token}});var importData=await importResponse.json();if(!importResponse.ok||!importData.ok)throw new Error(importData.error||('HTTP '+importResponse.status));var ip=importData.preview;
    document.getElementById('cashPreviewText').textContent+='\n\nФИНАЛЬНЫЙ IMPORT PREVIEW · данные не записаны\nСтрок кассы: '+ip.entries+'\nСобытий оплат: '+ip.paymentEvents+' (реальных: '+ip.realPaymentEvents+', восстановленных остатков: '+ip.balanceEvents+')\n'+ip.months.map(function(m){return m.month+' · Фил '+m.ownerReceived.toLocaleString('ru-RU')+' ₽ / ожидание '+m.ownerExpected.toLocaleString('ru-RU')+' ₽ · сделки Саши '+m.sashaSoldFor.toLocaleString('ru-RU')+' ₽ · доля toAgent '+m.sashaToAgent.toLocaleString('ru-RU')+' ₽ · строк '+m.entries;}).join('\n');
    if(ip.entries===108&&ip.paymentEvents===92)document.getElementById('cashImportControls').classList.remove('off');
    var workResponse=await fetch('http://127.0.0.1:8787/api/migration/work-preview',{headers:{Authorization:'Bearer '+token}});var workData=await workResponse.json();if(!workResponse.ok||!workData.ok)throw new Error(workData.error||('HTTP '+workResponse.status));var w=workData.preview;var workLines=['Данные не записаны','Проекты: '+w.projects.visible+' видимых, '+w.projects.hidden+' скрытых','Связи проектов: '+w.projects.readyRelations+' готовы, '+w.projects.heldRelations+' остаются спорными','Задачи: '+w.tasks.total+' · статусы '+JSON.stringify(w.tasks.statuses),'Связи задач: '+w.tasks.links.ready+' с готовыми проектами, '+w.tasks.links.held+' со спорными, '+w.tasks.links.missing+' без проекта','Задач с тегами: '+w.tasks.withTags+' · с переносами дедлайна: '+w.tasks.withDeadlineTransfers,'Журнал задач: '+w.taskLog.total,'Целевые наборы: '+w.goals.datasets.length+' (уникальных: '+w.goals.uniqueDatasetCount+')'];w.goals.datasets.forEach(function(g){workLines.push((g.month||'LIVE')+' · целей '+g.projects+' · '+JSON.stringify(g.stages)+(g.exactDuplicate?' · ТОЧНЫЙ ДУБЛЬ':'')+' · '+g.key);});workLines.push('Достижения: '+w.achievements.records);var workImportResponse=await fetch('http://127.0.0.1:8787/api/migration/work-import-preview',{headers:{Authorization:'Bearer '+token}});var workImportData=await workImportResponse.json();if(!workImportResponse.ok||!workImportData.ok)throw new Error(workImportData.error||('HTTP '+workImportResponse.status));var wi=workImportData.preview;workLines.push('','ФИНАЛЬНЫЙ IMPORT PREVIEW · данные не записаны','Проектов: '+wi.projects+' (без клиента: '+wi.unresolvedProjects+', скрытых новых: '+wi.hiddenProjects+')','Задач: '+wi.tasks,'Событий журнала: '+wi.taskLogs,'Уникальных целей: '+wi.goals,'Месячных состояний целей: '+wi.goalStates,'Достижений: '+wi.achievements);document.getElementById('workPreviewText').textContent=workLines.join('\n');document.getElementById('workPreview').classList.remove('off');if(wi.projects===74&&wi.tasks===77&&wi.taskLogs===127&&wi.goals===127&&wi.goalStates===301&&wi.achievements===2)document.getElementById('workImportControls').classList.remove('off');
    var contentResponse=await fetch('http://127.0.0.1:8787/api/migration/content-preview',{headers:{Authorization:'Bearer '+token}});var contentData=await contentResponse.json();if(!contentResponse.ok||!contentData.ok)throw new Error(contentData.error||('HTTP '+contentResponse.status));var cp=contentData.preview;document.getElementById('contentPreviewText').textContent=['Данные не записаны','КП: ключей '+cp.kp.keys+', черновиков '+cp.kp.drafts+', шаблонов '+cp.kp.templates+', полей в черновиках '+cp.kp.draftFields,'Договоры: сохранённых записей '+cp.contracts.storedRecords+'; режим '+cp.contracts.mode,'ADS: ключей '+cp.ads.keys+', расходы '+cp.ads.expenseDatasets+', рабочие наборы '+cp.ads.operationalDatasets+', служебные '+cp.ads.serviceDatasets,'Не попали в старый backup: '+cp.missingFromLegacyBackup.join(', ')].join('\n');document.getElementById('contentPreview').classList.remove('off');
    document.getElementById('mapLogin').classList.add('off');
  }
  document.getElementById('mapLoginBtn').addEventListener('click',async function(){var btn=this;btn.disabled=true;try{var response=await fetch(cfg.url+'/auth/v1/token?grant_type=password',{method:'POST',headers:{apikey:cfg.publishableKey,'Content-Type':'application/json'},body:JSON.stringify({email:document.getElementById('mapEmail').value.trim(),password:document.getElementById('mapPassword').value})});var auth=await response.json();if(!response.ok||!auth.access_token)throw new Error(auth.error_description||'Ошибка входа');document.getElementById('mapPassword').value='';sessionStorage.setItem(sessionKey,JSON.stringify({access_token:auth.access_token,expires_at:auth.expires_at}));await loadMap(auth.access_token);}catch(error){summary.textContent='Ошибка: '+error.message;btn.disabled=false;}});
  var current=getSession();if(current&&current.access_token)loadMap(current.access_token).catch(function(error){summary.textContent='Ошибка: '+error.message;});
  document.getElementById('cashImportConfirmation').addEventListener('input',function(){document.getElementById('cashImportBtn').disabled=this.value.trim()!=='ИМПОРТ КАССЫ 108 92';});
  document.getElementById('cashImportBtn').addEventListener('click',async function(){var current=getSession();if(!current||!current.access_token)return;var btn=this;btn.disabled=true;summary.textContent='Выполняю атомарный импорт кассы...';try{var response=await fetch('http://127.0.0.1:8787/api/migration/import-cash',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+current.access_token},body:JSON.stringify({checksum:activeChecksum,confirmation:'IMPORT_108_CASH_92_EVENTS'})});var data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||('HTTP '+response.status));var check=await fetch('http://127.0.0.1:8787/api/migration/cash-import-status',{headers:{Authorization:'Bearer '+current.access_token}});var checked=await check.json();if(!check.ok||!checked.ok)throw new Error(checked.error||'Status check failed');summary.textContent='ИМПОРТ КАССЫ ЗАВЕРШЁН · строк '+checked.status.entries+' · событий '+checked.status.events+' · реальных '+checked.status.realEvents+' · восстановленных '+checked.status.balanceEvents;btn.textContent='Касса импортирована';document.getElementById('cashImportConfirmation').disabled=true;}catch(error){summary.textContent='Ошибка импорта: '+error.message+' · транзакция отменена';btn.disabled=false;}});
  document.getElementById('workImportConfirmation').addEventListener('input',function(){document.getElementById('workImportBtn').disabled=this.value.trim()!=='ИМПОРТ РАБОТЫ 74 77 127 127 301 2';});
  document.getElementById('workImportBtn').addEventListener('click',async function(){var current=getSession();if(!current||!current.access_token)return;var btn=this;btn.disabled=true;summary.textContent='Импортирую проекты, задачи и цели...';try{var response=await fetch('http://127.0.0.1:8787/api/migration/import-work',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+current.access_token},body:JSON.stringify({checksum:activeChecksum,confirmation:'IMPORT_WORK_74_77_127_127_301_2'})});var data=await response.json();if(!response.ok||!data.ok)throw new Error(data.error||('HTTP '+response.status));var check=await fetch('http://127.0.0.1:8787/api/migration/work-status',{headers:{Authorization:'Bearer '+current.access_token}});var out=await check.json();if(!check.ok||!out.ok)throw new Error(out.error||'Status failed');summary.textContent='ИМПОРТ РАБОТЫ ЗАВЕРШЁН · '+JSON.stringify(out.status);btn.textContent='Задачи и цели импортированы';document.getElementById('workImportConfirmation').disabled=true;}catch(error){summary.textContent='Ошибка: '+error.message+' · транзакция отменена';btn.disabled=false;}});
  document.getElementById('contentConfirmation').addEventListener('input',function(){document.getElementById('contentImportBtn').disabled=this.value.trim()!=='ИМПОРТ КП ADS 51';});
  document.getElementById('contentImportBtn').addEventListener('click',async function(){var s=getSession(),b=this;if(!s)return;b.disabled=true;try{var r=await fetch('http://127.0.0.1:8787/api/migration/import-content',{method:'POST',headers:{'Content-Type':'application/json',Authorization:'Bearer '+s.access_token},body:JSON.stringify({checksum:activeChecksum,confirmation:'IMPORT_CONTENT_51'})});var d=await r.json();if(!r.ok||!d.ok)throw new Error(d.error);var q=await fetch('http://127.0.0.1:8787/api/migration/content-status',{headers:{Authorization:'Bearer '+s.access_token}}),o=await q.json();if(!q.ok||!o.ok)throw new Error(o.error);summary.textContent='ИМПОРТ КП/ADS ЗАВЕРШЁН · '+JSON.stringify(o.status);b.textContent='КП и ADS импортированы';document.getElementById('contentConfirmation').disabled=true;}catch(e){summary.textContent='Ошибка: '+e.message;b.disabled=false;}});
})();
